name: Deploy Website

on:
  push:
    branches:
      - master  # Trigger workflow on push to 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's automatically provided token
          publish_dir: ./  # The directory containing your website files (e.g., index.html)
          publish_branch: gh-pages  # Deploy to the 'gh-pages' branch
