name: Deploy Website

on:
  push:
    branches:
      - master  # Trigger workflow on push to 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Make sure this points to your website files
          publish_branch: gh-pages  # This pushes to the gh-pages branch
